### ISSUE TITLE
PopupMenu broken

### ISSUE THREAD

**Issue by luziferius** [luziferius/autokey#13]
## Classification:
Bug
## Reproducibility:
Always
## Summary

Hotkeys on folders don’t work.

## Steps to Reproduce

Use a Hotkey on a folder with a configured hotkey.
_OR:_
Check _Show in notification icon menu_
## Expected Results

- A popup menu should be shown.

## Actual Results
```
Traceback (most recent call last):
  File "/home/thomas/Projekte/autokey/lib/autokey/qtapp.py", line 371, in customEvent
    callback(*args)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtapp.py", line 350, in __createMenu
    self.menu = PopupMenu(self.service, folders, items, onDesktop, title)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtui/popupmenu.py", line 105, in __init__
    MenuBase.__init__(self, service, folders, items, onDesktop, title)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtui/popupmenu.py", line 55, in __init__
    subMenuItem = SubMenu(self._getMnemonic(folder.title), self, service, folder.folders, folder.items, False)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtui/popupmenu.py", line 120, in __init__
    MenuBase.__init__(self, service, folders, items, onDesktop)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtui/popupmenu.py", line 72, in __init__
    self._addItemsToSelf(items, onDesktop)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtui/popupmenu.py", line 89, in _addItemsToSelf
    self._addItem(item.description, item)
  File "/home/thomas/Projekte/autokey/lib/autokey/qtui/popupmenu.py", line 76, in _addItem
    self.addAction(action)
AttributeError: 'SubMenu' object has no attribute 'addAction'
```
## Version

qt4_ui_cleanup HEAD

**Comment by luziferius** [comment]
Refactored the whole thing. Works now even better, including matching item icons.
